<?php

namespace DR\PlatformBundle\Repository;

/**
 * ArtpurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtpurchaseRepository extends \Doctrine\ORM\EntityRepository
{
}
